- name: Install Java for PlantUML diagramming tool
  apt: pkg=default-jre
  become: yes

- name: Get plantuml
  get_url: url=https://github.com/plantuml/plantuml/releases/download/v1.2022.1/plantuml-1.2022.1.jar dest=/usr/share/java checksum=sha256:111995d0f54f18f5a6faa7f4e0360abc2fee9400d54595ca5fe6ab0ddeda1e61 mode=0755
  become: yes

- name: Create symbolic link
  file:
    src: "/usr/share/java/plantuml-1.2022.1.jar"
    dest: "/usr/share/java/plantuml.jar"
    state: link
  become: yes
