---
- hosts: all

  roles:
    - git
    - python
    - ansible
    - docker
    - packer
    - gh-md-to-html
    - plantuml

  post_tasks:
    - name: Set python3 as default python
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/lib/pyenv/shims/python3.8
      become: yes
